[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/login.html"
  status = 302

[functions]
  node_bundler = "esbuild"

[functions."generate-cr"]
  timeout = 26