-- La table profiles existe déjà dans le projet avec les colonnes id, first_name, last_name, account_type.
-- Le frontend Florita lit et écrit ces champs via auth.users.user_metadata (sb.auth.updateUser),
-- pas via la Data API — la table est marquée "API DISABLED" et n'est pas exposée via PostgREST.
-- Cette migration est intentionnellement vide.
